import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export async function getStaticProps(context) {
  return {
    props: { a: 222 }, // will be passed to the page component as props
  }
}

export default function Home({ a }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href='/aaa/xxx'>
        <a>About Us</a>
      </Link>
      <div>
        试试水
      </div>

      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    </div>
  )
}
