[package]
name = "eee-wasm"
version = "0.1.0"
authors = ["valor1990@yeah.net"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"