[package]
name = "jia-mi-vaolor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.83"
md5 = "0.7.0"

[lib]
crate-type = ["cdylib", "rlib"]