import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import Loading from '../loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next 66666',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, left, right }) {
  return (
    <div>
      <Suspense fallback={<Loading />}>
        <div className={inter.className}>{children}</div>
      </Suspense>
      <div>
        {left}
      </div>
      <div>
        {right}
      </div>
    </div>
  )
}
