import '@/app/globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App111',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/font/iconfont.css" />
        <Script src="/font/iconfont.js"></Script>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
